# Generated by Django 5.0 on 2024-02-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='start_date',
        ),
    ]
