# Generated by Django 5.0 on 2024-02-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_prescription_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='consumption_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
