# Generated by Django 5.0 on 2024-02-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_prescription_added_by_prescription_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='department',
        ),
    ]
