# Generated by Django 5.0 on 2024-02-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_prescription_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
