# Generated by Django 5.0.2 on 2024-02-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
