# Generated by Django 5.0.2 on 2024-02-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
