# Generated by Django 5.0.2 on 2024-02-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_remove_patient_gender_patient_is_female_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_female',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_male',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_other',
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
