# Generated by Django 5.0.2 on 2024-02-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0006_remove_patient_is_female_remove_patient_is_male_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
