# Generated by Django 5.0.2 on 2024-02-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0007_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(),
        ),
    ]
