# Generated by Django 5.0.2 on 2024-02-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0008_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
