# Generated by Django 5.0.2 on 2024-02-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0009_alter_patient_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
    ]
