# Generated by Django 5.0 on 2024-02-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0011_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
