# Generated by Django 5.0 on 2024-02-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0013_alter_appointment_token_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='token_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
