# Generated by Django 5.0 on 2024-02-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0014_alter_appointment_token_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
