# Generated by Django 5.0 on 2024-02-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0015_alter_patient_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
