# Generated by Django 5.0 on 2024-02-21 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0016_appointment_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
